import Foundation

// MARK: - Playbook Combo Key
enum PlaybookComboKey: String, CaseIterable {
    case maleFemale = "male_female"
    case femaleMale = "female_male"
    case maleMale = "male_male"
    case femaleFemale = "female_female"
    case `default` = "default"

    static func from(userGender: Gender, partnerGender: Gender) -> PlaybookComboKey {
        switch (userGender, partnerGender) {
        case (.male, .female): return .maleFemale
        case (.female, .male): return .femaleMale
        case (.male, .male): return .maleMale
        case (.female, .female): return .femaleFemale
        default: return .default
        }
    }
}

// MARK: - Playbook Category
struct PlaybookCategory: Identifiable {
    let id: String
    let title: String
    let emoji: String
    /// SF Symbol name for golden icon on iOS (emojis don't tint).
    let sfSymbol: String
}

// MARK: - Playbook Content
enum PlaybookContent {
    static let categories: [PlaybookCategory] = [
        PlaybookCategory(id: "how-to-dress", title: "How to Dress", emoji: "👔", sfSymbol: "tshirt.fill"),
        PlaybookCategory(id: "beauty-grooming", title: "Beauty & Grooming", emoji: "✨", sfSymbol: "sparkles"),
        PlaybookCategory(id: "chivalrous-actions", title: "Chivalrous Actions", emoji: "🤝", sfSymbol: "hand.raised.fill"),
        PlaybookCategory(id: "who-should-pay", title: "Who Should Pay", emoji: "💳", sfSymbol: "creditcard.fill"),
        PlaybookCategory(id: "body-language", title: "Body Language", emoji: "💬", sfSymbol: "bubble.left.and.bubble.right.fill"),
        PlaybookCategory(id: "how-to-plan-date", title: "How to Plan the Date", emoji: "📅", sfSymbol: "calendar"),
        PlaybookCategory(id: "texting-before-after", title: "Texting Before & After", emoji: "📱", sfSymbol: "message.fill"),
        PlaybookCategory(id: "physical-affection", title: "Physical Affection", emoji: "💕", sfSymbol: "heart.fill"),
        PlaybookCategory(id: "conversation-starters", title: "Conversation Starters", emoji: "💬", sfSymbol: "text.bubble.fill"),
        PlaybookCategory(id: "red-flags", title: "Red Flags to Avoid", emoji: "🚩", sfSymbol: "flag.fill"),
    ]

    static func tips(categoryId: String, comboKey: PlaybookComboKey) -> [String] {
        let byCombo = Self.tipsByCategory[categoryId]
        let tips = byCombo?[comboKey.rawValue] ?? byCombo?["default"]
        let fallback = byCombo?["default"] ?? []
        guard let t = tips, !t.isEmpty else { return fallback }
        return t
    }

    // Tips: [categoryId][comboKey] = [String]. At least 50 per (category, default); combo-specific when present.
    private static let tipsByCategory: [String: [String: [String]]] = [
        "how-to-dress": [
            "default": [
                "Dress for the venue, not for a fashion show—you want to look put-together, not overdressed.",
                "When in doubt, go one step smarter than you think the date calls for.",
                "Wear something you've worn before and feel confident in—new outfits can backfire.",
                "Clean, well-fitting clothes beat expensive labels every time.",
                "Avoid heavy cologne or perfume; a light scent or none is safer.",
                "Check the weather and dress for comfort as well as style.",
                "Shoes matter: clean, appropriate for the activity, and comfortable enough to walk in.",
                "If you're going somewhere nice, iron your clothes—wrinkles read as careless.",
                "Match your outfit to the activity so you're not under- or overdressed.",
                "Skip anything with offensive graphics, inside jokes, or political slogans.",
                "Neutral colors are a safe bet; bold colors can work if they suit you.",
                "Layer so you can adjust if the venue is hot or cold.",
                "Make sure your nails are clean and trimmed.",
                "Avoid looking like you're trying too hard—effort should look effortless.",
                "Dress in a way that feels like you, not like someone else's idea of a date.",
                "If the date is outdoors, choose fabrics that breathe and shoes that can get dirty.",
                "No gym clothes unless the date is literally the gym.",
                "A well-fitted jacket can elevate almost any look.",
                "Avoid wearing something that requires constant adjusting or fixing.",
                "When you look good, you act more confidently—so invest in a few go-to pieces.",
                "Dress for a slightly later hour than the actual time—evening dates deserve a bit more polish.",
                "Skip the baseball cap unless it's a very casual, daytime thing.",
                "Your outfit should say 'I care about this' without saying 'I spent all day on this.'",
                "If you're unsure about the dress code, a smart-casual look rarely fails.",
                "Avoid brand-new shoes that might give you blisters mid-date.",
                "Wear something that lets you move and sit comfortably.",
                "Dress in a way that wouldn't embarrass you if you ran into someone you know.",
                "One statement piece is enough—don't pile on accessories.",
                "Make sure your clothes are clean and smell fresh—no yesterday's shirt.",
                "Your date should remember you, not your outfit—so don't let clothes overshadow you.",
                "Dressing well shows respect for the other person and the occasion.",
                "If you're doing something active, dress for the activity first, style second.",
                "Avoid anything that could be a conversation stopper for the wrong reasons.",
                "A little color near your face can make you look more approachable.",
                "Fit matters more than trend—avoid too tight or too baggy.",
                "Dress so you're not constantly checking yourself in mirrors or windows.",
                "When the date could go long, choose clothes you can wear for hours comfortably.",
                "Avoid logos or branding that could distract or put people off.",
                "Your outfit should help you feel like the best version of yourself.",
                "Dress for the person you want to be on the date—confident, relaxed, present.",
                "No visible underwear, no stained clothes, no missing buttons.",
                "If you're going from day to evening, plan one outfit that works for both.",
                "Comfort and confidence go hand in hand—prioritize both.",
                "A clean, simple look often beats a busy or flashy one.",
                "Dress in a way that makes it easy for your date to imagine you in their life.",
                "Avoid looking like you're on your way to a different event.",
                "When in doubt, ask yourself: would I wear this to meet someone I really want to impress?",
                "Your clothes should support the conversation, not compete with it.",
                "Dress so that at the end of the night you still look like yourself—just a bit more polished.",
            ],
            "male_female": [], "female_male": [], "male_male": [], "female_female": [],
        ],
        "beauty-grooming": ["default": Self.defaultBeautyTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "chivalrous-actions": ["default": Self.defaultChivalrousTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "who-should-pay": ["default": Self.defaultWhoShouldPayTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "body-language": ["default": Self.defaultBodyLanguageTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "how-to-plan-date": ["default": Self.defaultHowToPlanDateTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "texting-before-after": ["default": Self.defaultTextingTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "physical-affection": ["default": Self.defaultPhysicalAffectionTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "conversation-starters": ["default": Self.defaultConversationStartersTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
        "red-flags": ["default": Self.defaultRedFlagsTips, "male_female": [], "female_male": [], "male_male": [], "female_female": []],
    ]

    private static let defaultBeautyTips: [String] = [
        "Skincare and grooming show you take care of yourself—it's not vanity, it's self-respect.",
        "Trim or groom facial hair so it looks intentional, not neglected.",
        "Clean, moisturized skin reads as put-together; dry or oily can read as careless.",
        "Teeth matter: brush, floss, and consider breath before a date.",
        "Nails don't have to be perfect, but they should be clean and trimmed.",
        "Hair should look intentional—styled or neatly kept, not like you just woke up.",
        "Avoid heavy makeup or product that could smear or need constant touching up.",
        "Less is more: a little grooming goes further than a full makeover right before the date.",
        "Deodorant is non-negotiable; fragrance is optional and should be light.",
        "Eyebrows frame your face—neat and natural beats overdone.",
        "Lips: hydrated and natural; avoid anything that will smear on glasses or when eating.",
        "If you wear makeup, make it look like you, not like a different person.",
        "Skin: address any obvious issues so you're not self-conscious.",
        "Hair should suit the venue—casual for coffee, a bit more polished for dinner.",
        "Avoid trying a new product or routine the day of the date—stick to what works.",
        "Eyes: rested when possible; if you're tired, own it rather than overdoing concealer.",
        "Grooming should enhance you, not hide you.",
        "Smell clean: shower, fresh clothes, light scent if any.",
        "Hands will be visible—clean nails, no rough cuticles.",
        "If you have a signature look, lean into it; don't change everything for one date.",
        "Avoid anything that could cause an allergic reaction or irritation mid-date.",
        "Grooming is for you first—when you feel good, you act more confidently.",
        "No food in teeth, no stray lipstick on teeth—quick check before you go.",
        "Hair should stay in place in wind or movement if you're going outside.",
        "Less product is better than too much—you want to look like yourself.",
        "Grooming should say 'I take care of myself' without saying 'I spent hours on this.'",
        "Skin should look healthy—hydration and sleep matter more than heavy coverage.",
        "Avoid trends that don't suit you; classic grooming rarely fails.",
        "Your date should remember your face, not your makeup or product.",
        "Grooming is part of showing up—for yourself and for the other person.",
        "No heavy fragrance that could trigger allergies or overwhelm.",
        "If you wear glasses, clean them; if you wear contacts, have backup if needed.",
        "Grooming should support the conversation, not distract from it.",
        "Avoid anything that could smear, melt, or need fixing during the date.",
        "Your best grooming is the version that makes you forget about how you look.",
        "Teeth and breath: non-negotiable; gum or mint if you're unsure.",
        "Nails: no chipped polish, no dirt; neutral is safe.",
        "Grooming should make you feel ready, not self-conscious.",
        "Less fragrance is better than more—you want to be remembered for you.",
        "Hair should look like it belongs to you—styled but not stiff.",
        "Skin: even if it's not perfect, clean and cared-for reads well.",
        "Avoid trying to look like someone else; groom to look like the best you.",
        "Your date should feel like they're with a person who takes care of themselves.",
        "Grooming is respect for yourself and for the occasion.",
        "No visible product buildup—hair, skin, or otherwise.",
        "Your best look is one where you don't have to think about your grooming.",
        "Grooming should support confidence, not replace it.",
    ]

    private static let defaultChivalrousTips: [String] = [
        "Hold the door when you're walking in or out together—it's a small sign of awareness.",
        "Offer to help with a coat or chair when it's natural; don't make a show of it.",
        "Pay attention to whether they need water, a napkin, or space—and respond.",
        "Walking on the street side is a classic gesture; do it if it feels right for you both.",
        "Put your phone away and give full attention—that's the most chivalrous move of all.",
        "If they're carrying something heavy, offer to help; accept a no gracefully.",
        "Listen more than you talk; showing interest is a form of respect.",
        "Remember small details they share and bring them up later—it shows you care.",
        "If plans change or there's a wait, take the lead on finding a solution.",
        "Offer to split or pay when the check comes, depending on your dynamic.",
        "Make eye contact when they're talking; don't scan the room.",
        "If they're cold, offer a jacket or suggest moving somewhere warmer.",
        "Thank the server and treat staff well—your date is watching.",
        "If something goes wrong, stay calm and focus on fixing it, not blaming.",
        "Offer to walk them to their car or wait for their ride if it's late.",
        "Don't interrupt; let them finish their thoughts.",
        "If they seem uncomfortable, check in: 'You good?' or 'Want to switch spots?'",
        "Hold space for silence; you don't have to fill every second.",
        "If you suggested the place, take responsibility for the vibe and any issues.",
        "Compliment something specific—effort, style, or something they said.",
        "Avoid being on your phone; if you must check it, say why and keep it brief.",
        "If they're tired or the date has run long, offer to wrap up without pressure.",
        "Show up on time—respecting their time is chivalrous.",
        "If they're not drinking and you are, don't push; match their energy.",
        "Offer the better seat or view if there's a choice.",
        "If something is clearly wrong—wrong order, bad table—take the lead on fixing it.",
        "Don't talk over them or dismiss their opinion; respect their perspective.",
        "If the date is going well, say so; clarity is kind.",
        "Leave room for them to contribute to plans; chivalry isn't control.",
        "If they need to leave early, be cool about it—no guilt or pressure.",
        "Thank them for the date at the end; a simple 'I had a great time' matters.",
        "Don't make them manage your emotions; stay even and present.",
        "If they're nervous, ease the vibe with warmth and humor.",
        "Offer to get the check or split in a way that feels fair to you both.",
        "Remember their name and use it occasionally—not in every sentence.",
        "If they're not feeling the venue, suggest moving; be flexible.",
        "Don't brag or one-up; let them shine.",
        "If they share something vulnerable, respond with empathy, not advice.",
        "Match their energy: if they're low-key, don't be over the top.",
        "If the date ends, end it well—no awkward lingering or pressure for more.",
        "Show that you're present: no glancing at other people or the room.",
        "If they're vegetarian or have dietary needs, respect that in where you go and what you order.",
        "Don't make them explain basic respect; you should already be doing it.",
        "If they offer to pay or split, respond graciously either way.",
        "Leave the date in a way that feels safe and clear for them.",
        "If you said you'd text or follow up, do it—follow-through is chivalrous.",
        "Don't make the date about you; make it about connection.",
        "If they're quiet, give them space; don't assume they're not having fun.",
        "Offer to help with directions or next steps if they're not from the area.",
        "End the date with a clear, kind sign-off—no mixed signals.",
    ]

    private static let defaultWhoShouldPayTips: [String] = [
        "Whoever asked for the date can offer to pay—but be ready to split or take turns.",
        "Splitting the check is always fair and avoids awkwardness.",
        "If one person paid this time, the other can get the next date—say that out loud.",
        "Don't assume; offer to pay or split and see how they respond.",
        "If you suggested the place, offering to pay is a nice gesture.",
        "If they insist on paying, thank them and offer to get the next one.",
        "Going Dutch is not unromantic—it's equitable and clear.",
        "If you're not sure, reach for the check and say 'I've got this' or 'Want to split?'",
        "Don't play games: if you want to pay, say so; if you want to split, say so.",
        "First date: splitting is the safest default unless one of you clearly offered.",
        "If they paid and you had a good time, say so and offer to get the next one.",
        "Don't make a big production of the check—handle it calmly.",
        "Whoever pays, the other should thank them sincerely.",
        "Taking turns paying on future dates is a good system if you keep seeing each other.",
        "If you're not comfortable with them paying for everything, say so kindly.",
        "Don't assume they'll pay just because of gender or who asked.",
        "If the bill is wrong, the person who's paying can take the lead on sorting it.",
        "Leaving a good tip matters—whoever pays should do it properly.",
        "If you want to pay, do it when the check comes—don't make it a debate.",
        "Splitting down the middle is fine; itemizing every penny can feel awkward.",
        "If you offered to pay and they want to split, let them—it's their choice.",
        "Don't use paying as a power move or to create obligation.",
        "Whoever pays should do it without making the other feel indebted.",
        "Be clear: 'I'll get this one' or 'Shall we split?' avoids confusion.",
        "Paying doesn't buy you anything—no entitlement, no expectation.",
        "Keep the check moment brief; then move on with the date.",
        "If you're not going to see them again, splitting is cleaner.",
        "If you're in a much different financial place, suggest something in your budget from the start.",
        "Second date: whoever didn't pay first can offer this time.",
        "Don't leave the other person wondering—communicate about the check.",
        "Taking someone out doesn't mean you own the date; stay respectful either way.",
        "If you paid and they don't offer to get the next one, that's data for you.",
        "Be clear so no one's left wondering.",
        "If you want to treat them, do it with a smile—not with strings attached.",
        "Whoever pays, the other should offer to help or thank them.",
        "Don't make paying a test; it's a practical decision.",
        "If you're not sure about the vibe, splitting is the safest bet.",
        "If they always want to pay and you're fine with it, still offer sometimes.",
        "Paying is a gesture, not a contract.",
        "If they offer to pay and you accept, don't then order the most expensive thing.",
        "Don't make a scene about paying; keep it low-key.",
        "First date: either split or the asker pays; both are valid.",
        "If they insist on paying and you're uncomfortable, offer to leave the tip.",
        "End the date in a way that feels clear for both of you.",
        "If you said you'd text or follow up, do it—follow-through matters.",
    ]

    private static let defaultBodyLanguageTips: [String] = [
        "Make eye contact when they're talking—but don't stare; natural breaks are fine.",
        "Lean in slightly when you're interested; it signals engagement.",
        "Uncross your arms; open body language reads as approachable.",
        "Nod when they make a point; it shows you're listening.",
        "Smile when it's genuine—forced smiles are easy to spot.",
        "Don't check your phone; nothing says 'I'm not present' like that.",
        "Face them; angling your body away can read as disinterest.",
        "Keep your hands visible; hiding them can read as nervous or closed off.",
        "Don't fidget too much; it can read as anxiety or boredom.",
        "Your feet pointing toward them signals interest.",
        "Don't look over their shoulder or scan the room while they talk.",
        "Relax your shoulders; tension shows in your body.",
        "If they're laughing, laugh with them—connection shows in shared reactions.",
        "Don't sit too far back; it can read as disengaged.",
        "If they pull back, give them space—don't push into their bubble.",
        "Your body language should say 'I'm here with you.'",
        "Don't cross your legs away from them; it can read as closed off.",
        "A slight tilt of the head when listening shows attention.",
        "Match their energy: if they're animated, you can be too; if they're calm, match that.",
        "Your posture should say you're comfortable and present.",
        "Keep your phone face-down or in your pocket.",
        "Your body language should support your words—not contradict them.",
        "Don't look at the door or the clock; it reads as wanting to leave.",
        "If you're into them, let it show in your eyes and posture.",
        "Don't invade their space; respect the bubble.",
        "If they seem closed off, don't push; stay open and warm.",
        "Sitting up straight reads as engaged; slouching can read as bored.",
        "Your body language should make them feel seen and heard.",
        "A warm smile when you make eye contact goes a long way.",
        "Your body language is part of the conversation.",
        "Don't look at other people; focus on your date.",
        "Relax; the best body language is natural and present.",
        "Mirror their energy and posture subtly; it builds rapport.",
        "Touch can be warm—a light touch on the arm when making a point—but read the room.",
        "If they lean in, you can lean in too—match their level of openness.",
        "If they touch your arm, you can respond with a smile or similar touch if it feels right.",
        "Don't touch your face too much; it can read as anxious or dishonest.",
        "If you're nervous, take a breath and settle into your seat.",
        "Don't lean back and cross your arms when they're sharing something personal.",
        "Relax your face; a resting frown can read as disapproval.",
        "If they're making eye contact, hold it for a few seconds then break naturally.",
        "Hand gestures when you talk are fine; they show energy and engagement.",
        "Don't play with your hair or jewelry excessively; it can read as nervous.",
        "Your goal is to make them feel comfortable and connected.",
        "If you're not sure, err on the side of open and attentive.",
    ]

    private static let defaultHowToPlanDateTips: [String] = [
        "Pick a place you've been to or have vetted—don't experiment on a first date.",
        "Consider the vibe: quiet enough to talk, not so quiet it's awkward.",
        "Match the plan to how well you know them—coffee for first meet, dinner if you've already clicked.",
        "Have a backup if the place is closed or packed.",
        "Suggest a specific time and place; 'we'll figure it out' can fizzle.",
        "Think about logistics: parking, transit, accessibility.",
        "Don't plan something that runs too long if you're not sure about the chemistry.",
        "If they have dietary needs or preferences, choose a place that works.",
        "A little research goes a long way—check hours, dress code, noise level.",
        "Leave room for the date to extend—don't book back-to-back things.",
        "If you're picking the place, own it—don't apologize excessively.",
        "Consider the time of day: brunch, lunch, dinner, or drinks each have a different vibe.",
        "Don't plan something that requires a lot of coordination or travel for a first date.",
        "If they suggest a place, be open to it—or suggest an alternative kindly.",
        "Have one or two backup ideas in case they're not into the first suggestion.",
        "Think about what you'll do if the date goes well—is there a natural next step nearby?",
        "Don't over-plan; leave room for spontaneity.",
        "If the date is outdoors, have a rain or weather backup.",
        "Choose a place where you can hear each other.",
        "Don't pick a place that's too fancy or too casual for the vibe you want.",
        "If you're meeting for the first time, pick somewhere public and easy to find.",
        "Consider their schedule—don't suggest a 3-hour dinner if they have an early start.",
        "If they're from out of town, offer to pick somewhere convenient for them.",
        "Don't plan something that puts them on the spot—e.g. karaoke if they're shy.",
        "A walk or activity can ease pressure compared to just sitting across a table.",
        "If you're not sure, suggest two options and let them choose.",
        "Think about the end of the date—is it easy to leave or extend?",
        "Don't pick a place that's known for bad service or long waits.",
        "If you have a favorite spot, share why you love it—it's a conversation starter.",
        "Consider budget: suggest something in a range that works for both.",
        "Don't plan something that requires a lot of prep or equipment unless you've agreed.",
        "If the first date goes well, have an idea for a second—different vibe, different activity.",
        "Leave buffer time so you're not rushed.",
        "Don't surprise them with a group or an event unless you've discussed it.",
        "Pick a place that reflects your personality—they're there to get to know you.",
        "If they suggest a time that doesn't work, offer a couple alternatives.",
        "Don't plan something that's all about you—e.g. only your favorite cuisine.",
        "Think about what happens after—drop-off, transit, or saying goodbye.",
        "A first date doesn't have to be dinner; coffee, drinks, or a walk are valid.",
        "Don't overthink it—a simple plan executed well beats a complicated one that falls apart.",
        "If you're picking the place, be ready to explain why you chose it.",
        "Consider noise level: you want to be able to talk.",
        "Don't plan something that could feel like a job interview—e.g. only formal dinner.",
        "Your goal is to create a setting where you can connect—everything else supports that.",
    ]

    private static let defaultTextingTips: [String] = [
        "Confirm the day before or the morning of—don't leave them wondering if it's still on.",
        "Keep the tone light before the date; save deeper conversation for in person.",
        "Don't over-text before the first date; leave something to talk about.",
        "If you need to reschedule, do it as soon as you know and offer a new time.",
        "After the date, if you had a good time, say so within 24–48 hours.",
        "Don't play games with response time; reply when you can, but don't leave them hanging.",
        "A simple 'I had a great time' or 'We should do this again' is enough after a first date.",
        "If you're not interested in a second date, don't ghost—a brief, kind message is better.",
        "Don't send a wall of text before you've met; keep it concise.",
        "If they don't reply for a while, one follow-up is fine; then leave it.",
        "After the date, don't wait days to text if you're interested—they'll wonder.",
        "Don't text while you're on the date with them; give them your full attention.",
        "Before the date, confirm place and time so you're both on the same page.",
        "If you're running late, text as soon as you know.",
        "Don't use texting to interview them before the date; save questions for in person.",
        "After a good date, you can suggest a specific second date idea in your text.",
        "Don't double-text repeatedly if they haven't replied; give it time.",
        "Keep the first post-date text simple; you don't need to write a novel.",
        "If they text you after the date, reply in a similar timeframe—don't play games.",
        "Before the date, a quick 'Looking forward to it' is nice; no need for more.",
        "If you're not interested after the date, don't say 'I'll text you' and then disappear.",
        "Don't send mixed signals—if you want to see them again, say so.",
        "After the date, if they don't text, you can reach out once if you want a second date.",
        "Don't over-analyze their texting style before you've met; in-person chemistry matters more.",
        "If you need to cancel, do it with enough notice and offer to reschedule if you mean it.",
        "After a first date, a text is enough; you don't have to call unless that's your vibe.",
        "Don't text about heavy or sensitive topics before the first date.",
        "If they suggest a time or place over text, respond clearly and confirm.",
        "After the date, don't wait for them to text first if you want to see them again.",
        "Don't leave the other person on read for days if you're interested.",
        "Before the date, one or two exchanges is plenty.",
        "If you're not sure about a second date, it's okay to take a day to think—but don't ghost.",
        "Don't use texting to build a false sense of intimacy before you've met.",
        "After the date, match their energy: if they're brief, be brief; if they're warm, be warm.",
        "Don't send goodnight or good morning texts before you've had a first date unless it's natural.",
        "If they don't reply after the date, take the hint—one follow-up max.",
        "Before the date, be clear about logistics so no one's confused.",
        "After a good date, saying 'I'd love to see you again' is clear and kind.",
        "Don't text when you're out with friends or busy; wait until you can focus.",
        "If you're both clearly into each other, texting can be a bit more frequent after the date.",
        "Don't use texting to test them—e.g. waiting hours to reply on purpose.",
        "After the date, if you had fun, say so; if you didn't, don't fake enthusiasm.",
        "Before the date, a simple confirmation reduces anxiety for both of you.",
        "If they text to reschedule, respond positively if you want to see them.",
        "Don't send long voice notes before you've met unless they've done it first.",
        "After the date, your text should reflect how you actually feel.",
        "Keep pre-date texting light and easy; save the real connection for in person.",
    ]

    private static let defaultPhysicalAffectionTips: [String] = [
        "Read the room: if they're keeping distance, don't push.",
        "A light touch on the arm when making a point can be warm—see how they respond.",
        "Don't assume the end of the date means a kiss; read their body language.",
        "If you want to kiss them, lean in slowly and give them a chance to respond.",
        "Hugging hello or goodbye is often a safe, warm gesture if it feels natural.",
        "If they pull back or seem uncomfortable, back off and don't make it a big deal.",
        "Match their level of touch: if they're not touching you, don't push it.",
        "Consent is ongoing—what's okay at one moment can change; pay attention.",
        "Don't use touch to test them or to create obligation.",
        "If they touch your arm or hand, you can respond in kind if it feels right.",
        "A kiss at the end of the date is not required; a warm goodbye is enough.",
        "If you're not sure, err on the side of less touch—you can always add more later.",
        "Don't touch their face or hair without clear signals they're into it.",
        "If they initiate touch, respond positively if you're comfortable.",
        "Holding hands can happen naturally if the vibe is right—don't force it.",
        "If you don't want to kiss or touch, say so or redirect kindly.",
        "Don't make a big deal if they don't want to kiss—respect their boundary.",
        "Touch should feel natural and mutual, not performative.",
        "If the date is going well, a brief touch on the hand or arm can signal interest.",
        "Don't escalate quickly; let the date breathe.",
        "If they're leaning in and making eye contact, they might be open to more touch.",
        "A hug goodbye is a safe way to show warmth without pressure.",
        "Don't touch them in a way that could feel possessive or entitled.",
        "If you're not into physical affection on the first date, that's okay—say so if needed.",
        "Match the setting: more touch might be okay in private; in public, keep it light.",
        "If they seem nervous, don't push touch—give them space.",
        "Touch should enhance the connection, not replace conversation.",
        "If you want more touch, create moments where it can happen naturally—e.g. sitting close.",
        "Don't assume that because they agreed to the date they want physical affection.",
        "If they say no or pull back, smile and move on—don't get awkward or pushy.",
        "A gentle touch on the back when walking can be sweet—read the room.",
        "Don't use alcohol as an excuse to push boundaries.",
        "If the vibe is clearly mutual, a kiss can be a natural end to the date.",
        "Don't make them ask you to stop; read their body language.",
        "Touch should feel good for both of you.",
        "If you're not sure they're into it, ask: 'Can I kiss you?' is clear and respectful.",
        "Don't linger in their space if they're not reciprocating.",
        "If they initiate a kiss, respond in kind if you want to—or turn your cheek kindly.",
        "Your goal is connection, not conquest—touch should support that.",
        "If the date ends with a handshake, that's okay—not every date ends in a kiss.",
        "Don't touch them in a way you wouldn't want to be touched.",
        "If they're open and warm, you can match that—gradually.",
        "Respect their boundaries even if you're disappointed.",
        "Touch is one way to connect; conversation and presence matter just as much.",
    ]

    private static let defaultConversationStartersTips: [String] = [
        "Ask about something they mentioned in their profile or earlier messages.",
        "What's something you're excited about right now?",
        "What did you do this week that was fun or interesting?",
        "How's your week been?—then actually listen to the answer.",
        "What's a place you've been that you'd go back to in a heartbeat?",
        "What's something you're looking forward to?",
        "Do you have any trips or plans coming up?",
        "What do you like to do when you're not working?",
        "What's the best thing you've seen or read lately?",
        "Is there a show, book, or podcast you're into right now?",
        "What's your go-to way to unwind?",
        "How did you get into [their job or hobby]?",
        "What's something that made you laugh recently?",
        "What's a food you could eat every day?",
        "Coffee or tea? Morning person or night owl?",
        "What's a skill you'd want to learn?",
        "What's the best advice you've gotten recently?",
        "Do you have a favorite spot in the city?",
        "What's something you're proud of lately?",
        "What's a movie or show you'd recommend?",
        "How's your family or friends doing?—if they've mentioned them.",
        "What's a cause or topic you care about?",
        "What's the best date you've been on?—can be funny or sweet.",
        "What's something that surprised you recently?",
        "What do you think about [something in the news or culture]?—keep it light.",
        "What's your ideal weekend look like?",
        "What's a hobby you've always wanted to try?",
        "What's the best meal you've had recently?",
        "How do you like to spend a day off?",
        "What's something you're curious about right now?",
        "What's a song or artist you've had on repeat?",
        "What's the best concert or event you've been to?",
        "What's a small thing that made your day recently?",
        "Do you cook? What's your go-to dish?",
        "What's a place you've always wanted to go?",
        "What's the best gift you've given or received?",
        "What's something you're working on—personally or professionally?",
        "What's your take on [something light]?",
        "What's a memory from childhood or travel that sticks with you?",
        "What's something that's been on your mind lately?",
        "What's the best compliment you've gotten?",
        "What's a tradition you love—family, holiday, or personal?",
        "What's something you're glad you tried?",
        "What's your ideal way to spend an evening?",
        "What's a question you wish people asked you more?",
        "What's something you're looking forward to this month?",
        "What's the best thing about your job or your day-to-day?",
        "What's a small win you had recently?",
        "What's something you'd do if you had a free day with no plans?",
        "What's a food or cuisine you've been wanting to try?",
        "What's the best thing that happened to you this week?",
    ]

    private static let defaultRedFlagsTips: [String] = [
        "They're rude to the server or staff—how they treat others is how they'll treat you.",
        "They talk only about themselves and don't ask you anything.",
        "They're on their phone the whole time or keep checking it.",
        "They badmouth their ex or past dates constantly.",
        "They pressure you to drink, eat, or do something you don't want to.",
        "They don't respect your boundaries—physical or emotional.",
        "They're vague about their life—job, where they live, plans—in a way that feels off.",
        "They make you feel stupid, wrong, or small.",
        "They're dismissive of your interests or opinions.",
        "They don't listen; they interrupt or talk over you.",
        "They're overly negative—about life, work, other people.",
        "They make inappropriate or offensive jokes and don't back off when you're not into it.",
        "They're pushy about physical affection or sex.",
        "They're evasive about basic questions—relationship status, kids, etc.",
        "They blame others for everything; nothing is ever their fault.",
        "They're condescending or talk down to you.",
        "They're inconsistent—hot and cold, or their story doesn't add up.",
        "They don't show up on time or communicate when they're late.",
        "They make you feel like you have to prove yourself.",
        "They're overly critical of your appearance, choices, or life.",
        "They don't ask you questions or show interest in your life.",
        "They're disrespectful of your time—late, canceling last minute, no apology.",
        "They talk about money in a way that makes you uncomfortable—bragging or complaining.",
        "They're not present—distracted, checking phone, looking around.",
        "They make you feel unsafe—physically or emotionally.",
        "They're controlling—telling you what to order, what to do, how to act.",
        "They don't take no for an answer—on small things or big.",
        "They're passive-aggressive or guilt-trip you.",
        "They have no curiosity about you or the world.",
        "They're mean to animals, kids, or people who can't do anything for them.",
        "They don't respect your no—on touch, on another drink, on anything.",
        "They're overly jealous or possessive on a first date.",
        "They trash their job, family, or friends constantly.",
        "They make everything about them—even your stories get turned back to them.",
        "They're not honest—little lies, exaggerations, or evasions.",
        "They don't make eye contact or engage when you talk.",
        "They're cheap in a way that feels disrespectful—e.g. not tipping, splitting to the penny in a mean way.",
        "They pressure you to go somewhere else or extend the date when you've said you need to go.",
        "They're arrogant—can't admit they're wrong or don't know something.",
        "They don't apologize when they've clearly done something wrong.",
        "They make you feel like you're not enough.",
        "They're flaky—cancel, reschedule, or disappear without a good reason.",
        "They don't respect your boundaries when you say you're not comfortable.",
        "They're negative about your interests or the things you love.",
        "They talk over you or correct you in a mean way.",
        "They don't show basic respect—for your time, your body, your opinions.",
        "If something feels off, trust your gut—you don't owe them a second chance.",
        "They're not kind—to you, to others, or to themselves in a healthy way.",
        "They make you feel like you have to walk on eggshells.",
        "They don't take responsibility for their actions.",
        "They're not interested in getting to know you—only in performing or impressing.",
    ]
}
